-- =====================================================================
-- MedKitt — Auto-generated UPDATE SQL for changed nodes
-- Generated: 2026-07-16
-- Review carefully, then paste into Supabase SQL Editor.
-- =====================================================================

BEGIN;

-- Node: uti-uncomplicated (2 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":3,"title":"Uncomplicated Cystitis","body":"**Uncomplicated cystitis** = lower UTI in non-pregnant premenopausal woman with no complicating factors. [1][2]\n\n**Criteria (ALL must be met):**\n• Female\n• Non-pregnant\n• No structural/functional urinary tract abnormalities\n• No recent instrumentation\n• Not immunocompromised\n• Lower urinary tract symptoms only (no fever/flank pain)\n\n**First-Line Treatment Options:**\n\n**1. Nitrofurantoin** (PREFERRED)\n• 100mg BID x 5 days\n• Excellent E. coli coverage\n• Low resistance rates\n• Avoid if CrCl <30\n\n**2. TMP-SMX**\n• 1 DS tab BID x 3 days\n• Use only if local resistance <20%\n• Avoid if recent TMP-SMX use\n\n**3. Fosfomycin**\n• 3g single dose\n• Slightly lower efficacy\n• Good for compliance concerns\n\n**4. Pivmecillinam** (Pivya — FDA-approved Apr 2024)\n• 185mg PO TID x 3–7 days\n• First-line per IDSA; minimal collateral damage to gut flora\n• Useful when other first-line agents unsuitable (allergy, resistance)\n\n**AVOID for uncomplicated cystitis:**\n• Fluoroquinolones (reserve for complicated/pyelo)\n• Beta-lactams other than pivmecillinam (lower cure rates)","citation":[1,2],"next":"uti-uncomplicated-treatment","calculatorLinks":[{"id":"crcl-cockcroft-gault","label":"CrCl Calculator"}],"summary":"Nitrofurantoin 100mg BID x5d preferred, TMP-SMX x3d if resistance <20%, fosfomycin single dose, pivmecillinam 185mg TID x3-7d — avoid FQ for cystitis"}'::jsonb
WHERE id = 'uti-uncomplicated' AND tree_id = 'adult-uti';

-- Node: sui-documentation (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":5,"title":"Documentation Requirements","body":"**Joint Commission (NPSG.15.01.01 — renumbered NPSG.08.01.01 in the 2026 standards) requirements:** [2]\n\n**Document all of:**\n☐ Validated screening tool used (C-SSRS) and results\n☐ Risk factors identified (list specific ones)\n☐ Protective factors identified\n☐ Collateral obtained (family, records, outpatient providers)\n☐ Mental status examination\n☐ Lethal means assessment and counseling provided\n☐ Risk stratification with rationale\n☐ Safety plan completed (copy in chart)\n☐ Disposition decision and clinical rationale\n☐ Specific follow-up plan with appointment details\n☐ Crisis resources provided\n\n**Sentinel Event Note:**\nSuicide within **7 days** of ED discharge is now a sentinel event (updated 2024). [2]\n\n**Key phrases for documentation:**\n• \"Patient denied active suicidal ideation with intent or plan\"\n• \"Lethal means counseling provided regarding [specific means]\"\n• \"Safety plan completed collaboratively with patient\"","citation":[2],"summary":"C-SSRS, risk/protective factors, means assessment, safety plan, disposition rationale — suicide within 7 days = sentinel event","safetyLevel":"critical"}'::jsonb
WHERE id = 'sui-documentation' AND tree_id = 'suicide-risk-assessment';

-- Node: vt-mono-stable (2 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":4,"title":"Stable Monomorphic VT — IV Antiarrhythmic","body":"**Monomorphic stable VT — IV antiarrhythmic.**\n\n**First-line options:**\n• [Amiodarone](#/drug/amiodarone/stable vt) 150 mg IV over 10 min → 1 mg/min × 6h → 0.5 mg/min\n• [Procainamide](#/drug/procainamide/stable vt) 20–50 mg/min until arrhythmia suppresses, hypotension, QRS widens >50%, or max 17 mg/kg\n• [Lidocaine](#/drug/lidocaine/stable vt) 1–1.5 mg/kg → 0.5–0.75 mg/kg q5–10 min → infusion 1–4 mg/min\n\n**Procainamide may be preferred** (2025 AHA: procainamide Class IIa vs amiodarone Class IIb) — higher termination rates and fewer major cardiac adverse events than amiodarone for hemodynamically stable VT (PROCAMIO) [8].\n\n**⚠️ Avoid procainamide** if prolonged QTc at baseline (Torsades risk) **or in CHF / significantly impaired LV function** — amiodarone is preferred in these patients (2025 AHA).","citation":[2,3,5,7,8],"next":"vt-mono-response","summary":"Amiodarone 150mg/10min OR procainamide (preferred per 2025 AHA IIa vs IIb); avoid procainamide if prolonged QTc or CHF/impaired LV → use amiodarone","safetyLevel":"warning"}'::jsonb
WHERE id = 'vt-mono-stable' AND tree_id = 'ventricular-tachycardia';

-- Citations changed — DELETE and re-INSERT
DELETE FROM tree_citations WHERE tree_id = 'ventricular-tachycardia';
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 1, 'Farkas J. Ventricular Tachycardia. EMCrit Internet Book of Critical Care. https://emcrit.org/ibcc/vt/');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 2, 'American Heart Association. 2025 Guidelines for CPR and ECC — Part 9: Adult Advanced Life Support. Circulation. 2025. (Supersedes Panchal AR, et al. 2023 AHA Focused Update on ACLS.)');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 3, 'Al-Khatib SM, et al. 2017 AHA/ACC/HRS Guideline for Management of Patients With Ventricular Arrhythmias and the Prevention of Sudden Cardiac Death. Circulation. 2018;138(13):e272-e391.');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 4, 'Soar J, et al. European Resuscitation Council Guidelines 2021: Advanced Life Support. Resuscitation. 2021;161:115-151.');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 5, 'First10EM. Wide Complex Tachycardia. https://first10em.com/');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 6, 'Nickson C. Ventricular Tachycardia. Life in the Fast Lane. https://litfl.com/');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 7, 'Priori SG, et al. 2015 ESC Guidelines for the Management of Patients with Ventricular Arrhythmias and the Prevention of Sudden Cardiac Death. Eur Heart J. 2015;36(41):2793-2867.');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 8, 'Ortiz M, et al. Randomized Comparison of Intravenous Procainamide vs. Intravenous Amiodarone for the Acute Treatment of Tolerated Wide QRS Tachycardia. J Am Coll Cardiol. 2017;69(4):491.');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 9, 'Kudenchuk PJ, et al. Amiodarone, Lidocaine, or Placebo in Out-of-Hospital Cardiac Arrest (ALPS Trial). N Engl J Med. 2016;374:1711-1722.');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 10, 'Callaway CW, et al. Part 8: Post-Cardiac Arrest Care. 2015 AHA Guidelines Update for CPR and ECC. Circulation. 2015;132(18 Suppl 2):S465-S482.');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 11, 'Brugada J, et al. 2019 ESC Guidelines for the Management of Patients with Supraventricular Tachycardia. Eur Heart J. 2020;41(5):655-720.');
INSERT INTO tree_citations (tree_id, num, text) VALUES ('ventricular-tachycardia', 12, 'Tung R, et al. Catheter Ablation of Ventricular Tachycardia. Circulation. 2020;142(2):e1-e17.');

COMMIT;