-- =====================================================================
-- MedKitt — Auto-generated UPDATE SQL for changed nodes
-- Generated: 2026-07-31
-- Review carefully, then paste into Supabase SQL Editor.
-- =====================================================================

BEGIN;

-- Node: wrist-start (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"question","module":0,"title":"Wrist Injury Assessment","body":"Wrist injuries account for ~15% of ED orthopedic visits. Recognition of fracture patterns, associated dislocations, and neurovascular compromise is critical.\n\n**Mechanism guides injury pattern:**\n• **FOOSH (fall on outstretched hand)** → distal radius, scaphoid, perilunate dislocation\n• **Fall on dorsum of hand** → Smith fracture, triquetral fracture\n• **Direct blow to hypothenar** → hamate hook fracture\n• **High-energy hyperextension** → perilunate/lunate dislocation\n• **Forced rotation** → DRUJ dislocation, TFCC tear\n\n**Red flags requiring emergent management:**\n• Neurovascular compromise (absent pulses, motor deficit, median nerve symptoms)\n• Open fracture\n• Compartment syndrome\n• Obvious dislocation\n• Tense swelling with skin tenting [1][2]","citation":[1,2],"options":[{"label":"Distal radius fracture","description":"","next":"wrist-distal-radius"},{"label":"Carpal bone fracture","description":"","next":"wrist-carpal-type"},{"label":"Perilunate/lunate dislocation","description":"","next":"wrist-peri-lunate"},{"label":"DRUJ dislocation","description":"","next":"wrist-druj"},{"label":"Ligament injury (TFCC, scapholunate)","description":"","next":"wrist-ligament"},{"label":"Soft tissue injury / uncertain","description":"","next":"wrist-imaging"}],"summary":"Mechanism-based triage: FOOSH, dorsal fall, direct blow, high-energy; assess neurovascular status first"}'::jsonb
WHERE id = 'wrist-start' AND tree_id = 'wrist-injuries';

-- Node: wrist-dr-which-type (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"question","module":1,"title":"Distal Radius Fracture Classification","body":"Based on radiographs, what type of distal radius fracture?","citation":[1],"options":[{"label":"Colles (dorsal angulation)","description":"","next":"wrist-colles"},{"label":"Smith (volar angulation)","description":"","next":"wrist-smith"},{"label":"Barton (rim fracture + carpal dislocation)","description":"","next":"wrist-barton"}],"summary":"Classify by radiograph: Colles (dorsal angulation), Smith (volar), or Barton (rim + carpal dislocation)"}'::jsonb
WHERE id = 'wrist-dr-which-type' AND tree_id = 'wrist-injuries';

-- Node: wrist-carpal-type (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"question","module":2,"title":"Carpal Bone Fracture Identification","body":"**Carpal bone fracture frequency:**\n1. **Scaphoid** — 60-70% (most common)\n2. **Triquetrum** — 15% (second most common)\n3. **Lunate** — 0.5-4%\n4. **Hamate** — 2-4%\n5. **Others** — trapezium, trapezoid, capitate, pisiform (rare)\n\n**Clinical exam guides diagnosis:**\n• Snuffbox tenderness → scaphoid\n• Dorsal ulnar tenderness → triquetrum\n• Central dorsal wrist pain → lunate\n• Hypothenar pain → hamate\n\n**⚠️ High-risk fractures for AVN:**\n• Scaphoid (proximal pole)\n• Lunate (Kienböck disease)\n\nBoth have retrograde blood supply → immobilize aggressively [7]","citation":[7],"options":[{"label":"Scaphoid (snuffbox tenderness)","description":"","next":"wrist-scaphoid"},{"label":"Triquetrum (dorsal ulnar pain)","description":"","next":"wrist-triquetrum"},{"label":"Lunate (central wrist pain)","description":"","next":"wrist-lunate"},{"label":"Hamate (hypothenar pain)","description":"","next":"wrist-hamate"}],"summary":"Scaphoid 60-70% of carpal fractures; scaphoid and lunate at high AVN risk due to retrograde blood supply"}'::jsonb
WHERE id = 'wrist-carpal-type' AND tree_id = 'wrist-injuries';

-- Node: wrist-ligament (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"question","module":4,"title":"Wrist Ligament Injury Type","body":"**Two major ligamentous injuries:**\n\n**1. Scapholunate Dissociation**\n• Disruption of scapholunate interosseous ligament\n• Radial-sided wrist pain\n• \"Terry Thomas sign\" (gap >5mm on PA X-ray)\n• Progressive SLAC wrist if untreated\n\n**2. TFCC (Triangular Fibrocartilage Complex) Tear**\n• Ulnar-sided wrist pain\n• Clicking with forearm rotation\n• Associated with DRUJ instability\n• Often requires MRI or arthroscopy for diagnosis\n\nBoth can be occult on plain films. Clinical suspicion guides management [21][22]","citation":[21,22],"options":[{"label":"Scapholunate dissociation (radial pain, widened gap)","description":"","next":"wrist-sl-dissoc"},{"label":"TFCC tear (ulnar pain, clicking, DRUJ instability)","description":"","next":"wrist-tfcc"}],"summary":"Scapholunate: radial pain, Terry Thomas sign >5mm gap; TFCC: ulnar pain, clicking with rotation"}'::jsonb
WHERE id = 'wrist-ligament' AND tree_id = 'wrist-injuries';

COMMIT;