-- =====================================================================
-- MedKitt — Auto-generated UPDATE SQL for changed nodes
-- Generated: 2026-05-03
-- Review carefully, then paste into Supabase SQL Editor.
-- =====================================================================

BEGIN;

-- Node: ab-mixed-result (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"result","module":3,"title":"Mixed: Metabolic + Respiratory Acidosis","body":"The measured pCO2 exceeds the predicted range from Winter''s formula.\n\n**Both metabolic AND respiratory processes are contributing to acidemia.** This is a particularly dangerous combination — the pH drops further than either process alone would cause.\n\n**Common scenarios:**\n• COPD exacerbation + sepsis\n• Sedation/opioid use + DKA\n• Neuromuscular disease + renal failure\n• Post-arrest (metabolic acidosis + hypoventilation)","citation":[4,12,17],"recommendation":"Address both processes urgently. Maximize ventilatory support. Treat the metabolic cause. Consider sodium bicarbonate if pH ≤ 7.20 with AKI (BICAR-ICU criteria).","confidence":"recommended"}'::jsonb
WHERE id = 'ab-mixed-result' AND tree_id = 'acid-base';

-- Node: ab-treatment (2 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":6,"title":"Treatment Considerations","body":"**Sodium Bicarbonate:**\n[Sodium Bicarbonate](#/drug/sodium-bicarbonate/metabolic acidosis) — indications, dosing, and evidence.\n\n**Indications for bicarbonate:** [12][17]\n• pH ≤ 7.20 with moderate-to-severe AKI (BICAR-ICU: NNT 6 for 28-day mortality)\n• TCA overdose (sodium channel blockade)\n• Salicylate toxicity (urinary alkalinization)\n• Life-threatening hyperkalemia\n• Bicarbonate-losing conditions (severe diarrhea, RTA)\n\n**Note:** BICAR-ICU enrolled pH ≤ 7.20 + AKIN 2-3. The pH < 6.9 threshold is ADA guidance for DKA specifically.\n\n**NOT recommended:** [3][17]\n• Routine cardiac arrest or CPR\n• Routine DKA (unless pH < 6.9 per ADA)\n• Routine lactic acidosis (no hemodynamic benefit proven)\n\n[Fluid Selection Guide](#/info/ab-fluids-guide) — NS vs balanced crystalloids.","citation":[1,2,3,12,13,17],"next":"ab-disposition","calculatorLinks":[{"id":"anion-gap","label":"Anion Gap"},{"id":"stewart-sig","label":"Stewart SID/SIG"}],"summary":"Bicarb for pH≤7.20 with AKI (BICAR-ICU), TCA OD, salicylate tox, severe hyperK — NOT routine in DKA or lactic acidosis","safetyLevel":"warning"}'::jsonb
WHERE id = 'ab-treatment' AND tree_id = 'acid-base';

-- Node: croup-mild-tx (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":2,"title":"Mild Croup — Glucocorticoid Only","body":"**Single dose glucocorticoid is standard of care for ALL severities of croup.**\n\n**First-line:**\n• [Dexamethasone](#/drug/dexamethasone) **0.6 mg/kg PO** (max 16 mg) — single dose\n\n**Non-inferior alternatives:**\n• [Dexamethasone](#/drug/dexamethasone) **0.15 mg/kg PO** — lower dose equally effective [3][6]\n• [Prednisolone](#/drug/prednisolone) **1 mg/kg PO** — non-inferior symptom relief, BUT higher re-presentation rate (29% vs 7% with dex) [6]\n\n**If unable to tolerate oral:**\n• [Budesonide](#/drug/budesonide-neb) **2 mg nebulized** — effective alternative [5][9]\n• [Dexamethasone](#/drug/dexamethasone) **0.6 mg/kg IM**\n\n**NNT = 7** to prevent one return visit. Reduces return visits/readmissions by ~50%. Safe single-dose profile.","citation":[1,2,3,5,6,8],"next":"croup-mild-obs","summary":"Dexamethasone 0.6 mg/kg PO single dose for ALL severities — NNT 7 to prevent return visit"}'::jsonb
WHERE id = 'croup-mild-tx' AND tree_id = 'croup';

-- Node: diarrhea-cdiff (1 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":3,"title":"C. difficile Evaluation","body":"**Suspect C. difficile if:**\n• Antibiotic use in past **3 months** (especially clindamycin, fluoroquinolones, cephalosporins)\n• Recent hospitalization or nursing home residence\n• Diarrhea developing **≥3 days after hospitalization** (C. diff testing has 15-20% yield in nosocomial diarrhea vs <5% for standard stool cultures)\n\n**Testing:**\n• **C. difficile toxin assay** — preferred: NAAT (PCR) or GDH + toxin two-step algorithm\n• Toxin A/B immunoassay alone has lower sensitivity\n\n**Key management:**\n• **STOP the offending antibiotic** if possible\n• Start empiric treatment if strong clinical suspicion — stop if toxin assay returns negative\n\n**Severity classification:**\n• **Non-severe:** WBC ≤15K, Cr <1.5\n• **Severe:** WBC >15K, Cr >1.5, albumin <3\n• **Fulminant:** hypotension, ileus, megacolon → surgical consult","citation":[1,5,6],"next":"diarrhea-cdiff-treatment","summary":"C. diff: stop offending antibiotic, fidaxomicin 200mg BID x 10d preferred (IDSA/SHEA 2021) — admit severe/fulminant","safetyLevel":"warning"}'::jsonb
WHERE id = 'diarrhea-cdiff' AND tree_id = 'diarrhea';

-- Node: diarrhea-cdiff-treatment (3 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"result","module":3,"title":"C. difficile Treatment","body":"**Non-severe (first episode):** [IDSA/SHEA 2021]\n• [Fidaxomicin](#/drug/fidaxomicin/c difficile) **200 mg PO BID × 10 days** (PREFERRED — lower recurrence)\n• Alternative: [Vancomycin](#/drug/vancomycin/c difficile) 125 mg PO QID × 10 days\n• Metronidazole only if fidaxomicin/vancomycin unavailable\n\n**Severe (WBC >15K, Cr >1.5):**\n• [Fidaxomicin](#/drug/fidaxomicin/c difficile) 200 mg PO BID × 10 days (preferred)\n• OR [Vancomycin](#/drug/vancomycin/c difficile) 125 mg PO QID × 10 days\n• Do NOT use metronidazole alone for severe disease\n\n**Fulminant (hypotension, ileus, megacolon):**\n• [Vancomycin](#/drug/vancomycin/c difficile) 500 mg PO/NG QID\n• PLUS [Metronidazole](#/drug/metronidazole/c difficile) 500 mg IV q8h\n• Consider rectal vancomycin enema if ileus present\n• **Surgical consult** — colectomy may be lifesaving\n\n**Disposition:** Admit severe and fulminant cases. Non-severe may be discharged with close follow-up.\n\n[Special Populations](#/node/diarrhea-special-pops)","citation":[5,6],"recommendation":"Stop offending antibiotic. Fidaxomicin is preferred first-line (lower recurrence than vancomycin). Admit severe and fulminant cases.","treatment":{"firstLine":{"drug":"Fidaxomicin","dose":"200 mg","route":"PO","frequency":"BID","duration":"10 days","notes":"Preferred per IDSA/SHEA 2021 — lower recurrence rate than vancomycin."},"alternative":{"drug":"Vancomycin","dose":"125 mg","route":"PO","frequency":"QID","duration":"10 days","notes":"Alternative if fidaxomicin unavailable. Increase to 500 mg PO/NG QID for fulminant disease."},"monitoring":"WBC, creatinine, clinical response. Surgical consult for fulminant cases (hypotension, ileus, megacolon)."},"confidence":"definitive","summary":"C. difficile Treatment — determine disposition and follow-up plan based on clinical findings"}'::jsonb
WHERE id = 'diarrhea-cdiff-treatment' AND tree_id = 'diarrhea';

-- Node: osteo-abx-mssa (2 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":3,"title":"Empiric Antibiotics - MSSA Coverage","body":"**First-line MSSA regimen:** [1,3]\n\n[Cefazolin](#/drug/cefazolin/osteomyelitis) 40 mg/kg IV q8h (max 6g/day)\n- Excellent MSSA coverage\n- Good bone penetration\n- Low risk of resistance induction\n\n**Alternative:**\n[Nafcillin](#/drug/nafcillin/pediatric MSSA osteomyelitis) 50 mg/kg IV q6h\n- More narrow spectrum\n- Higher rates of phlebitis\n\n**Transition to oral:**\n[Cephalexin](#/drug/cephalexin/osteomyelitis) 25-30 mg/kg PO q8h\n- Excellent bioavailability\n- First-line for oral step-down\n\n**If cultures return MRSA:** Escalate to vancomycin or clindamycin based on sensitivities. [1]","citation":[1,3],"next":"osteo-surgical-consult","treatment":{"firstLine":{"drug":"Cefazolin","dose":"40 mg/kg","route":"IV","frequency":"q8h","duration":"Until clinical improvement, then transition to oral","notes":"Max 6g/day; good bone penetration"},"alternative":{"drug":"Nafcillin","dose":"50 mg/kg","route":"IV","frequency":"q6h","duration":"Until clinical improvement","notes":"Monitor for phlebitis"},"monitoring":"CRP trend; clinical response; watch for culture results"}}'::jsonb
WHERE id = 'osteo-abx-mssa' AND tree_id = 'peds-osteomyelitis';

-- Node: osteo-abx-young (2 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":3,"title":"Empiric Antibiotics - Age <4 Years","body":"***Kingella kingae* considerations:** [5,9]\n\n*K. kingae* is the **most common pathogen** in children 6 months - 4 years in many regions. [5]\n\n**Characteristics:**\n- Fastidious organism - standard cultures often negative\n- Requires PCR or enriched culture techniques\n- Mild clinical presentation (low-grade fever, modest CRP)\n- Excellent prognosis with appropriate treatment [5,9]\n\n**K. kingae antibiotic sensitivities:**\n- Susceptible to: Beta-lactams, aminoglycosides, fluoroquinolones\n- **Resistant to:** Vancomycin, clindamycin [5,9]\n\n**First-line regimen:**\n[Cefazolin](#/drug/cefazolin/osteomyelitis) 40 mg/kg IV q8h\n- Covers both *K. kingae* AND *S. aureus*\n- Do NOT use clindamycin alone in this age group\n\n**Oral step-down:**\n[Amoxicillin-clavulanate](#/drug/amoxicillin-clavulanate/osteomyelitis) or cephalexin","citation":[5,9],"next":"osteo-surgical-consult","treatment":{"firstLine":{"drug":"Cefazolin","dose":"40 mg/kg","route":"IV","frequency":"q8h","duration":"Until improvement, then oral transition","notes":"Covers Kingella AND S. aureus; do NOT use clindamycin alone <4 years"},"alternative":{"drug":"Amoxicillin-clavulanate","dose":"90 mg/kg/day (amoxicillin component)","route":"PO","frequency":"divided q12h","duration":"Oral step-down option","notes":"Good Kingella coverage; alternative for oral transition"},"monitoring":"Clinical response; CRP trend; consider K. kingae PCR if available"}}'::jsonb
WHERE id = 'osteo-abx-young' AND tree_id = 'peds-osteomyelitis';

-- Node: xyl-start (2 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"question","module":1,"title":"Xylazine Toxicity — Initial Assessment","body":"**Xylazine Quick Reference** — key facts at a glance.\n\n**What is Xylazine (\"Tranq\")?**\n• **Alpha-2 adrenergic agonist** (same class as clonidine, dexmedetomidine)\n• FDA-approved for veterinary use ONLY — not approved for humans\n\n**The epidemic (2025 update):**\n• **MEDETOMIDINE now dominant** in some markets — detected in **72% of Philadelphia samples** (Oct-Dec 2024), while xylazine dropped from 98% to 31% [CDC MMWR April 2025]\n• Medetomidine is **10x more potent** than xylazine — expect more severe sedation and bradycardia\n• Same management principles apply (alpha-2 agonist toxidrome)\n\n**Critical point:** These drugs are **NOT reversed by naloxone** — they are not opioids. However, **still give naloxone** because 95% of exposures involve fentanyl co-ingestion [1][2].\n\nWhat is the patient''s current presentation?","citation":[1,2],"options":[{"label":"Acute overdose presentation","description":"Respiratory depression, altered mental status, recent use","next":"xyl-oa2a"},{"label":"Skin wounds present","description":"Necrotic ulcers, non-healing wounds, may or may not be at injection sites","next":"xyl-wound-assess"},{"label":"Withdrawal symptoms","description":"Restless, anxious, tachycardic — recent cessation of use","next":"xyl-withdrawal"}],"calculatorLinks":[{"id":"xyl-wound-staging","label":"Xylazine Wound Staging"},{"id":"xyl-withdrawal-comparison","label":"Tranq vs Opioid Withdrawal"}],"summary":"Alpha-2 agonist NOT reversed by naloxone — medetomidine now 72% of Philly supply (10x more potent than xylazine)","safetyLevel":"critical"}'::jsonb
WHERE id = 'xyl-start' AND tree_id = 'xylazine-toxicity';

-- Node: xyl-withdrawal (2 field(s) changed)
UPDATE decision_nodes SET data = '{"type":"info","module":5,"title":"Xylazine Withdrawal","body":"**Timeline:** Symptoms begin **4-6 hours** after last use (faster than opioid withdrawal)\n\n**Tranq vs Opioid Withdrawal Comparison**\n\n**Xylazine/medetomidine withdrawal symptoms (NOT reversed by opioids):**\n• Anxiety, irritability, restlessness, dysphoria\n• Tachycardia, diaphoresis, hypertension\n• **No GI symptoms** (unlike opioid withdrawal)\n\n**Key difference from opioid withdrawal:**\n• Buprenorphine/methadone do NOT treat xylazine withdrawal\n• Must address BOTH if patient uses tranq dope [1][5]","citation":[1,5],"next":"xyl-withdrawal-tx","summary":"Symptoms begin 4-6h after last use (faster than opioids); no GI symptoms; buprenorphine does NOT treat it"}'::jsonb
WHERE id = 'xyl-withdrawal' AND tree_id = 'xylazine-toxicity';

COMMIT;