BEGIN;

-- syncope: sync-disposition-low
UPDATE decision_nodes SET body = E'**Low-risk patients should generally be discharged**, even with unexplained syncope. [1,2]\n\n**Low-risk features (ESC):** [2]\n• Young age with typical features of reflex syncope\n• No history of cardiac disease\n• Syncope only when standing\n• Identifiable trigger (pain, blood, prolonged standing)\n• Normal ECG\n• Normal vital signs\n\n**Discharge counseling:**\n• Explain diagnosis and expected benign prognosis\n• Counsel on avoidance of known triggers\n• Counterpressure maneuvers (leg crossing, hand gripping) for prodromal symptoms\n• Adequate hydration and salt intake\n• Review fall risk and injury prevention\n\n**Recurrence:** ~9% recurrence within 6 months; 3+ lifetime episodes most predictive of future recurrence [49]\n\n**Driving:** Be familiar with state laws regarding driving after syncope. Consider referral before return to work for commercial drivers or high-risk occupations. [50]\n\n**Follow-up:** PCP for recurrent or unexplained syncope.\n\n[Discharge Instructions](#/info/syncope-discharge) — shareable patient handout', recommendation = E'Discharge with reassurance, trigger avoidance counseling, and PCP follow-up. Address driving restrictions if applicable. Review [Discharge Instructions](#/info/syncope-discharge) with patient.' WHERE id = 'sync-disposition-low' AND tree_id = 'syncope';

-- syncope: sync-orthostatic-disposition
UPDATE decision_nodes SET body = E'**Medication or volume-related orthostatic syncope** with otherwise reassuring evaluation.\n\n**Management:**\n• IV fluids if volume-depleted\n• Review and adjust offending medications\n• Educate on slow position changes\n• Compression stockings and increased salt/fluid intake for recurrent episodes\n• PCP follow-up for medication adjustment\n\n**Important:** In elderly patients, identifying orthostasis allows modification of fall risk factors (medications), but orthostasis alone should NOT be the sole factor in risk stratification. [23,24]', recommendation = E'Low to intermediate risk. Treat volume depletion, adjust medications, PCP follow-up for med reconciliation. Review [Discharge Instructions](#/info/syncope-discharge) with patient.' WHERE id = 'sync-orthostatic-disposition' AND tree_id = 'syncope';

-- burns: burn-discharge-result
UPDATE decision_nodes SET body = E'**Appropriate for superficial or small partial-thickness burns <5% TBSA** in patients with reliable follow-up, adequate social support, and ability to perform dressing changes.\n\n**Discharge criteria:**\n• Pain controlled with oral medications\n• Patient/family demonstrates ability to perform dressing changes\n• No signs of inhalation injury\n• No circumferential burns\n• No concern for NAT\n• Adequate follow-up arranged\n\n**Discharge instructions:**\n• **Daily dressing changes:** Gentle wash with soap and water, apply bacitracin ointment, cover with nonadherent dressing and gauze wrap\n• **Keep burned area elevated** above heart level when possible\n• **Pain management:** Ibuprofen 400-800mg q6-8h + acetaminophen 1000mg q6-8h around the clock for first 48-72h\n• **Avoid sun exposure** on healing burns for 12 months (permanent hyperpigmentation)\n\n**Return precautions:**\n• Increasing pain, redness, or swelling around the burn\n• Purulent drainage or foul odor\n• Fever >100.4°F (38°C)\n• Burn appearance worsening (deepening)\n• Inability to manage pain at home\n\n**Follow-up:** 24-48 hours for wound reassessment. Earlier if concern for deepening. Tetanus update if >5 years or unknown.\n\n[Discharge Instructions](#/info/burns-discharge) — shareable patient handout', recommendation = E'Superficial or small partial thickness <5% TBSA. Adequate oral pain control. Daily dressing changes (bacitracin + nonadherent). Keep elevated. Return if increasing pain/redness/drainage/fever. Follow-up 24-48h. Tetanus if >5y or unknown. Review [Discharge Instructions](#/info/burns-discharge) with patient.' WHERE id = 'burn-discharge-result' AND tree_id = 'burns';

-- chest-tube: ctube-disposition
UPDATE decision_nodes SET body = E'AFTER SUCCESSFUL TUBE REMOVAL\n• Confirm lung remains expanded on post-removal CXR\n• If recurrent pneumothorax on post-removal film: small and asymptomatic may observe; large or symptomatic requires new tube\n\nDISCHARGE PLANNING\n• Wound care: keep dressing clean and dry, remove in 48 hours\n• Activity: avoid heavy lifting or straining for 1-2 weeks\n• No air travel until confirmed resolution (minimum 2 weeks post)\n• No scuba diving until pulmonology clearance\n• Smoking cessation counseling\n\nRECURRENCE\n• PSP: ~30% at 1 year, ~50% lifetime\n• SSP: ~40-50% recurrence\n• After 2nd ipsilateral episode: strongly recommend pleurodesis (VATS with mechanical pleurodesis or stapled bullectomy)\n\nFOLLOW-UP\n• Outpatient CXR in 2-4 weeks\n• Pulmonology referral for: SSP, recurrent PSP, pleurodesis discussion\n\n[Discharge Instructions](#/info/chest-tube-discharge) — shareable patient handout', recommendation = E'Discharge with follow-up CXR in 2-4 weeks. Smoking cessation and activity restrictions. Pulmonology referral if recurrent or SSP. Review [Discharge Instructions](#/info/chest-tube-discharge) with patient.' WHERE id = 'ctube-disposition' AND tree_id = 'chest-tube';

-- distal-radius: dr-dispo
UPDATE decision_nodes SET body = E'**DISCHARGE INSTRUCTIONS:**\n• **Elevation** — keep hand above heart for 48 hours to minimize swelling\n• **Ice** — 20 min on / 20 min off over cast padding\n• **Finger exercises** — wiggle fingers frequently to prevent stiffness\n• **Neurovascular checks** — ensure fingers remain pink, warm, with normal sensation\n\n**RETURN IMMEDIATELY IF:**\n• Increasing pain not relieved by elevation and medication\n• Numbness, tingling, or inability to move fingers\n• Fingers turn blue, white, or cold\n• Cast feels too tight or causes pressure sores\n\n**COMPARTMENT SYNDROME WARNING:**\nAny of the above symptoms could indicate compartment syndrome — a surgical emergency.\n\n**FOLLOW-UP:**\n• **Ortho clinic in 5–7 days** for repeat films\n• 1-week x-ray checks for re-displacement (especially first 2 weeks)\n• Cast duration: typically 4–6 weeks for adults, 3–4 weeks for children\n\n[Discharge Instructions](#/info/distal-radius-discharge) — shareable patient handout', recommendation = E'Successful reduction. Discharge with elevation, ice, finger exercises, neurovascular check instructions, and ortho follow-up in 5–7 days. Review [Discharge Instructions](#/info/distal-radius-discharge) with patient.' WHERE id = 'dr-dispo' AND tree_id = 'distal-radius';

-- hiv: hiv-discharge
UPDATE decision_nodes SET body = E'**Discharge criteria:**\n• Stable vital signs, able to tolerate PO\n• No suspected OI requiring inpatient treatment\n• Well-controlled HIV with manageable complaint\n• Reliable follow-up available\n\n**Discharge instructions:**\n• Continue all HIV medications as prescribed — **do NOT stop HAART**\n• Follow up with HIV provider within 1-2 weeks (or sooner per complaint)\n• Return for worsening symptoms, new fever, inability to take medications\n\n**Linkage to care opportunities:**\n• If not engaged in HIV care → provide contact information for local HIV clinic\n• If PEP started → arrange follow-up in 3-7 days for adherence check\n• If PrEP candidate identified → refer to PrEP provider\n• If newly diagnosed → urgent HIV specialist referral (same day if possible)\n• If untested → offer HIV testing before discharge or provide referral\n\n**The ED visit is a critical touchpoint** — 80% of new transmissions come from those not diagnosed or not in care. Identifying and linking these patients is one of the highest-impact interventions the ED can provide. [1]\n\n[Discharge Instructions](#/info/hiv-ed-discharge) — shareable patient handout', recommendation = E'Discharge with continued HAART. Follow up with HIV provider. Link to care if not engaged. Offer HIV testing if untested. Refer for PEP/PrEP as indicated. Review [Discharge Instructions](#/info/hiv-ed-discharge) with patient.' WHERE id = 'hiv-discharge' AND tree_id = 'hiv';

-- meningitis: mening-discharge
UPDATE decision_nodes SET body = E'**Discharge criteria (extrapolated from pediatric data, use clinical judgment):** [23]\n• Nontoxic clinical appearance\n• Normal serum WBC count\n• Mild CSF pleocytosis only\n• Negative CSF Gram stain\n• Adequate symptom control (headache, nausea, vomiting)\n• Reliable support system and follow-up capability\n\n**Return precautions — discuss thoroughly:**\n• Worsening headache\n• Vomiting\n• Confusion or behavioral changes\n• Seizures\n• Fever >38.5°C\n• Neck stiffness worsening\n\n**Follow-up:** Primary care within **3 days** for reassessment. [23]\n\n[Discharge Instructions](#/info/meningitis-discharge) — shareable patient handout', recommendation = E'Outpatient management of low-risk viral meningitis with strict return precautions and 3-day follow-up. Review [Discharge Instructions](#/info/meningitis-discharge) with patient.' WHERE id = 'mening-discharge' AND tree_id = 'meningitis';

COMMIT;