BEGIN;
-- 5. drugs (2 new drugs)
INSERT INTO drugs (id, name, generic_name, drug_class, route, indications, dosing, contraindications, cautions, monitoring, notes, image, citations, sort_order) VALUES
('hydrocortisone', 'Hydrocortisone (Solu-Cortef)', 'Hydrocortisone sodium succinate', 'Corticosteroid (glucocorticoid + mineralocorticoid)', 'IV / IM / PO',
 '["Adrenal crisis (adult)","Adrenal crisis (pediatric)","Stress dose (moderate illness/surgery)","Maintenance (adult)","Maintenance (pediatric)","Emergency IM self-injection"]'::jsonb,
 '[{"indication":"Adrenal crisis (adult)","regimen":"100 mg IV or IM bolus immediately. Then 200 mg/24h as continuous infusion (preferred) or 50 mg IV every 6 hours. Taper to oral maintenance over 1-3 days as hemodynamics stabilize. At doses ≥50 mg/day, fludrocortisone is NOT needed."},{"indication":"Stress dose (moderate illness/surgery)","regimen":"50 mg IV or PO every 8 hours for the duration of physiologic stress. Taper to maintenance dose over 2-3 days after resolution. For major surgery: 100 mg IV preop, then 200 mg/24h, taper as above."},{"indication":"Maintenance (adult)","regimen":"15-25 mg PO daily, divided BID or TID. Give 2/3 dose upon waking, 1/3 in early afternoon (last dose >6 hours before bedtime). Typical regimen: 15 mg AM + 5 mg at 2 PM. Use lowest effective dose to avoid Cushingoid features."},{"indication":"Pediatric adrenal crisis","regimen":"50 mg/m² IV bolus (max 100 mg). Then 50-100 mg/m²/day as continuous infusion or divided every 6-8 hours. Requires BSA calculation — use BSA Calculator. Weight-based approximation: ~2 mg/kg IV bolus.","weightCalc":{"dosePerKg":2,"unit":"mg","maxDose":100,"label":"Approximation (~50 mg/m²)"}},{"indication":"Pediatric maintenance","regimen":"6-10 mg/m²/day PO divided TID. Monitor growth velocity — overtreatment suppresses linear growth. Use BSA Calculator for precise dosing."},{"indication":"Emergency IM self-injection","regimen":"100 mg IM into lateral thigh. For patients unable to take oral steroids due to vomiting or altered mental status. Must present to ED immediately after injection for evaluation and IV steroids."}]'::jsonb,
 '["Systemic fungal infections (relative — do NOT withhold in adrenal crisis)"]'::jsonb,
 '["Hyperglycemia with stress dosing — monitor glucose frequently","Sodium retention and fluid overload at high doses","At doses ≥50 mg/day, provides sufficient mineralocorticoid effect — fludrocortisone not needed","Immunosuppression with prolonged supraphysiologic dosing","Adrenal suppression if used chronically at supraphysiologic doses — taper slowly"]'::jsonb,
 'Blood glucose (especially during stress dosing). Electrolytes (Na, K). Blood pressure. Growth velocity in children. Plasma renin activity for fludrocortisone titration.',
 'First-line corticosteroid for adrenal crisis and maintenance replacement. Preferred because it is structurally identical to endogenous cortisol, provides both glucocorticoid AND mineralocorticoid activity, and has a short half-life (~90 minutes) allowing physiologic diurnal dosing. Cortisol half-life of 90 minutes means systemic effects of deficiency may develop within hours. Continuous infusion may provide more stable cortisol levels than intermittent boluses.',
 NULL,
 '["Bornstein SR, et al. Diagnosis and Treatment of Primary Adrenal Insufficiency: An Endocrine Society Clinical Practice Guideline. JCEM. 2016;101(2):364-389.","Rushworth RL, et al. Adrenal Crisis. N Engl J Med. 2019;381(9):852-861.","Husebye ES, et al. Adrenal Insufficiency. Lancet. 2021;397(10274):613-629."]'::jsonb,
 0)
;

INSERT INTO drugs (id, name, generic_name, drug_class, route, indications, dosing, contraindications, cautions, monitoring, notes, image, citations, sort_order) VALUES
('methylprednisolone', 'Methylprednisolone (Solu-Medrol)', 'Methylprednisolone sodium succinate', 'Corticosteroid (glucocorticoid)', 'IV / PO',
 '["Adrenal crisis (alternative to hydrocortisone)"]'::jsonb,
 '[{"indication":"Adrenal crisis (alternative)","regimen":"40 mg IV every 24 hours. Use ONLY when hydrocortisone is unavailable. Minimal mineralocorticoid activity — consider adding fludrocortisone once transitioned to maintenance doses in patients with primary adrenal insufficiency."}]'::jsonb,
 '["Systemic fungal infections (relative — do NOT withhold in adrenal crisis)"]'::jsonb,
 '["Minimal mineralocorticoid activity — inferior to hydrocortisone for adrenal crisis where both glucocorticoid and mineralocorticoid replacement are needed","Hyperglycemia","Immunosuppression with prolonged use"]'::jsonb,
 'Blood glucose, electrolytes (Na, K), blood pressure, fluid status.',
 'Second-line alternative for adrenal crisis when hydrocortisone is unavailable. Glucocorticoid potency is ~5× hydrocortisone (4 mg methylprednisolone = 20 mg hydrocortisone), but has minimal mineralocorticoid effect. Preferred over dexamethasone when some mineralocorticoid activity is desired.',
 NULL,
 '["Rushworth RL, et al. Adrenal Crisis. N Engl J Med. 2019;381(9):852-861.","Bornstein SR, et al. Diagnosis and Treatment of Primary Adrenal Insufficiency. JCEM. 2016;101(2):364-389."]'::jsonb,
 1)
;


-- 5b. drugs — UPDATE existing entries (3 drugs)
-- Updating Dexamethasone with full current data (includes new burn dosing entries)
UPDATE drugs SET
  indications = '["Croup (standard of care)","Cerebral edema","Antiemetic (chemotherapy)","Bacterial meningitis (adjunctive)","Airway edema","Adrenal crisis (alternative)","Adrenal maintenance (alternative)"]'::jsonb,
  dosing = '[{"indication":"Croup","regimen":"0.6 mg/kg PO as a single dose (max 16 mg). Low-dose alternative: 0.15 mg/kg PO (non-inferior). If unable to tolerate oral: 0.6 mg/kg IM.","weightCalc":[{"dosePerKg":0.6,"unit":"mg","maxDose":16,"label":"Standard dose"},{"dosePerKg":0.15,"unit":"mg","label":"Low-dose alternative"}]},{"indication":"Cerebral edema","regimen":"10 mg IV loading dose, then 4 mg IV/IM q6h."},{"indication":"Airway edema / post-extubation stridor","regimen":"0.5 mg/kg IV q6h x 4 doses, starting 12-24 hours before planned extubation.","weightCalc":{"dosePerKg":0.5,"unit":"mg"}},{"indication":"Bacterial Meningitis (adjunctive)","regimen":"0.15 mg/kg IV q6h × 2-4 days. Give WITH or up to 15-20 min BEFORE first antibiotic dose. Reduces mortality in pneumococcal meningitis (Cochrane 2015). STOP if Listeria or Cryptococcus identified — worsened outcomes.","weightCalc":{"dosePerKg":0.15,"unit":"mg","dailyDivided":4}},{"indication":"Adrenal crisis (alternative)","regimen":"4 mg IV every 24 hours. Use when hydrocortisone is unavailable OR when cosyntropin stimulation test is planned — dexamethasone does NOT cross-react with cortisol assays, allowing meaningful cortisol measurement during treatment. Zero mineralocorticoid activity — add fludrocortisone for primary AI once on maintenance."},{"indication":"Adrenal maintenance (alternative)","regimen":"0.25-0.5 mg PO once daily. Long half-life (~36 hours) allows once-daily dosing. No mineralocorticoid activity — must add fludrocortisone for primary AI. Higher growth suppression risk in children compared to hydrocortisone."}]'::jsonb,
  contraindications = '["Systemic fungal infections","Known hypersensitivity to dexamethasone"]'::jsonb,
  cautions = '["Single-dose use for croup is safe with minimal adverse effects","Hyperglycemia with repeated dosing — monitor glucose in diabetics","Immunosuppression with prolonged use — not a concern with single dose","May mask signs of infection with prolonged use"]'::jsonb,
  monitoring = 'Clinical response. For croup: reassess severity 2-3 hours after dose. For prolonged use: blood glucose, signs of infection.',
  notes = 'Standard of care for croup in ALL severities. A 2023 Cochrane review (45 RCTs, 5,888 children) showed glucocorticoids significantly reduce croup scores at 2, 6, 12, and 24 hours vs placebo. NNT = 7 to prevent one return visit. Single dose provides sustained benefit due to long half-life (~36 hours). Reduces return visits/readmissions by ~50% (RR 0.52). Low-dose (0.15 mg/kg) is non-inferior to standard dose in a 1,252-patient RCT.',
  citations = '["Aregbesola A, et al. Glucocorticoids for Croup in Children. Cochrane Database Syst Rev. 2023;1:CD001955.","Bjornson CL, et al. A Randomized Trial of a Single Dose of Oral Dexamethasone for Mild Croup. N Engl J Med. 2004;351(13):1306-13.","Parker CM, Cooper MN. Prednisolone Versus Dexamethasone for Croup: A Randomized Controlled Trial. Pediatrics. 2019;144(3):e20183772.","Gates A, Johnson DW, Klassen TP. Glucocorticoids for Croup in Children. JAMA Pediatrics. 2019;173(6):595-596."]'::jsonb
WHERE id = 'dexamethasone';

-- Updating Fludrocortisone with full current data (includes new burn dosing entries)
UPDATE drugs SET
  indications = '["Hyperkalemia (adjunct — stimulates renal K+ excretion)","Adrenal insufficiency","Orthostatic hypotension","Adrenal insufficiency maintenance (PAI only)","Pediatric AI maintenance"]'::jsonb,
  dosing = '[{"indication":"Hyperkalemia adjunct","regimen":"0.2 mg PO once. Especially useful in patients on ACEi/ARB, tacrolimus, or with suspected type IV RTA."},{"indication":"Adrenal insufficiency maintenance (PAI only)","regimen":"50-200 μg (0.05-0.2 mg) PO once daily. For PRIMARY adrenal insufficiency only — NOT needed in secondary or tertiary AI (renin-angiotensin-aldosterone axis intact). Starting dose: 50-100 μg. Titrate based on plasma renin activity (target normal range), blood pressure, and serum potassium."},{"indication":"Pediatric AI maintenance","regimen":"50-200 μg PO daily. Higher doses may be needed in infants with salt-wasting congenital adrenal hyperplasia. Salt supplementation 1-2 g/day may be needed in infants. Monitor blood pressure, serum potassium, and plasma renin activity.","weightCalc":{"dosePerKg":0.05,"unit":"mg","maxDose":0.2,"label":"Starting dose — titrate to renin"}}]'::jsonb,
  contraindications = '["Systemic fungal infections","Active heart failure (sodium retention)"]'::jsonb,
  cautions = '["Sodium retention → fluid overload, edema, hypertension","Hypokalemia with prolonged use","Consider if patient making urine but K+ not falling (inadequate urine K+ content)"]'::jsonb,
  monitoring = 'Blood pressure, serum potassium, fluid status.',
  notes = 'Underutilized adjunct for hyperkalemia. Replaces the mineralocorticoid effect suppressed by ACEi/ARBs, tacrolimus, and other causes of type IV RTA. Stimulates ENaC sodium reabsorption and ROMK potassium secretion in the collecting duct. Most effective when combined with adequate sodium delivery to the collecting duct (i.e., after volume resuscitation).',
  citations = '["Palmer BF, Clegg DJ. Diagnosis and Treatment of Hyperkalemia. Cleve Clin J Med. 2017;84(12):934-942."]'::jsonb
WHERE id = 'fludrocortisone';

-- Updating Prednisolone with full current data (includes new burn dosing entries)
UPDATE drugs SET
  indications = '["Croup (alternative to dexamethasone)","Asthma exacerbation","Inflammatory conditions","Adrenal maintenance (alternative)"]'::jsonb,
  dosing = '[{"indication":"Croup","regimen":"1 mg/kg PO as a single dose (max 60 mg). Non-inferior to dexamethasone 0.6 mg/kg in a 1,252-patient RCT.","weightCalc":{"dosePerKg":1,"unit":"mg","maxDose":60}},{"indication":"Asthma exacerbation","regimen":"1-2 mg/kg/day PO (max 60 mg) for 3-5 days.","weightCalc":{"dosePerKg":2,"unit":"mg","maxDose":60}},{"indication":"Adrenal maintenance (alternative)","regimen":"3-5 mg PO once daily. Alternative to hydrocortisone for adrenal insufficiency maintenance. Advantage: once-daily dosing improves adherence. Available as liquid formulation for children. No mineralocorticoid activity — must add fludrocortisone for primary AI."}]'::jsonb,
  contraindications = '["Systemic fungal infections","Known hypersensitivity"]'::jsonb,
  cautions = '["Shorter half-life than dexamethasone (~12-36 hours vs ~36 hours) — may need additional doses for prolonged symptoms","Available as liquid formulation — easier for young children who cannot swallow tablets","Bitter taste — may cause vomiting in some children"]'::jsonb,
  monitoring = 'Clinical response. For croup: reassess severity 2-3 hours after dose.',
  notes = 'Non-inferior alternative to dexamethasone for croup based on Parker et al. (2019) — 1,252 children randomized to prednisolone 1 mg/kg vs dexamethasone 0.6 mg/kg showed equivalent outcomes for symptom relief and 7-day return visits. Advantage: widely available as liquid formulation. Disadvantage: shorter half-life means symptoms may recur, and bitter taste may cause vomiting.',
  citations = '["Parker CM, Cooper MN. Prednisolone Versus Dexamethasone for Croup: A Randomized Controlled Trial. Pediatrics. 2019;144(3):e20183772.","Aregbesola A, et al. Glucocorticoids for Croup in Children. Cochrane Database Syst Rev. 2023;1:CD001955."]'::jsonb
WHERE id = 'prednisolone';


-- 6. info_pages (6 pages)
INSERT INTO info_pages (id, title, subtitle, sections, citations, shareable, sort_order) VALUES
('ai-summary', 'Adrenal Insufficiency Steps Summary', 'Stepwise management of adrenal crisis and chronic AI',
 '[{"heading":"1. Crisis Recognition & Resuscitation","body":"• [Assess clinical presentation](#/node/ai-start)\n• [Confirm crisis features — SBP ≤100 or ≥20 below baseline](#/node/ai-crisis-confirm)\n• [Immediate IV fluids — 1L NS (peds: 20 mL/kg)](#/node/ai-crisis-fluids)\n• [Emergency steroids — Hydrocortisone 100 mg IV](#/node/ai-crisis-steroid)"},{"heading":"2. Crisis Treatment","body":"• [Ongoing management — HC 200 mg/24h](#/node/ai-crisis-ongoing)\n• [Response assessment at 1-2 hours](#/node/ai-crisis-response)\n• [Identify and treat precipitant](#/node/ai-precipitant-workup)\n• [Refractory shock — broaden differential](#/node/ai-crisis-refractory)"},{"heading":"3. Type Classification","body":"• [PAI vs SAI vs TAI](#/node/ai-type-classify)\n• [Primary AI — Addison''s disease](#/node/ai-pai-workup)\n• [Secondary AI — pituitary](#/node/ai-sai-workup)\n• [Tertiary AI — steroid-induced](#/node/ai-tai-workup)"},{"heading":"4. Diagnostic Workup","body":"• [Morning cortisol + ACTH](#/node/ai-diagnostic-labs)\n• [Cosyntropin stimulation test](#/node/ai-cosyntropin)"},{"heading":"5. Maintenance & Stress Dosing","body":"• [Maintenance therapy — HC 15-25 mg PO daily](#/node/ai-maintenance)\n• [Sick-day rules — double/triple dose](#/node/ai-stress-dose)\n• [Medication-related triggers](#/node/ai-med-related)\n• [Crisis prevention & patient education](#/node/ai-prevention)"},{"heading":"6. Disposition","body":"• [ICU — active crisis / hemodynamic instability](#/node/ai-dispo-icu)\n• [Floor — acute illness / new diagnosis](#/node/ai-dispo-admit)\n• [Discharge — stable with follow-up](#/node/ai-dispo-discharge)"}]'::jsonb,
 '[]'::jsonb,
 false,
 0)
;

INSERT INTO info_pages (id, title, subtitle, sections, citations, shareable, sort_order) VALUES
('ai-precipitants', 'Precipitating Factors & Differential Diagnosis', 'Common triggers for adrenal crisis and diagnostic mimics',
 '[{"heading":"Crisis Precipitants","body":"**Infection** — #1 trigger overall (viral in children, bacterial in adults) [1]\n**GI illness** — vomiting prevents oral steroid absorption\n**Surgery / trauma** — inadequate stress dosing perioperatively\n**Steroid withdrawal** — abrupt cessation of chronic glucocorticoids\n**CYP3A4 inducers** — rifampin, phenytoin, carbamazepine, phenobarbital accelerate cortisol metabolism\n**Adrenal hemorrhage** — anticoagulation, meningococcemia (Waterhouse-Friderichsen), antiphospholipid syndrome\n**Emotional stress** — significant psychological stressors\n**Temperature extremes** — heat or cold exposure\n**No identifiable trigger** — ~10% of cases [2]"},{"heading":"Differential Diagnosis","body":"**Shock** — septic, hypovolemic, cardiogenic, obstructive\n**Endocrine emergencies** — thyroid storm, myxedema coma, DKA, HHS\n**GI** — acute abdomen, gastroenteritis, dehydration\n**Cardiac** — acute MI, Takotsubo cardiomyopathy\n**Other** — anorexia nervosa, TCA overdose (can mimic adrenal crisis)"},{"heading":"Clinical Clues Favoring Adrenal Crisis","body":"• Shock refractory to fluids AND vasopressors\n• Hyperpigmentation (palmar creases, buccal mucosa)\n• Hyponatremia + hyperkalemia (PAI)\n• Hypoglycemia without diabetes or insulin use\n• Known chronic steroid use with missed doses\n• History of autoimmune disease\n• Rapid improvement after parenteral hydrocortisone (1-2 hours)"}]'::jsonb,
 '[{"num":1,"text":"Rushworth RL, Torpy DJ, Falhammar H. Adrenal Crisis. N Engl J Med. 2019;381(9):852-861."},{"num":2,"text":"Hahner S, et al. High Incidence of Adrenal Crisis in Educated Patients. JCEM. 2015;100(2):407-416."},{"num":3,"text":"Lentz S, et al. Diagnosis and Management of Adrenal Insufficiency in the ED. J Emerg Med. 2022;63(2):212-220."}]'::jsonb,
 false,
 1)
;

INSERT INTO info_pages (id, title, subtitle, sections, citations, shareable, sort_order) VALUES
('ai-lab-findings', 'Lab Findings by AI Type', 'Distinguishing primary, secondary, and tertiary adrenal insufficiency',
 '[{"heading":"Laboratory Comparison","body":"","drugTable":[{"drug":"Cortisol","regimen":"LOW in all types. AM cortisol <3 μg/dL virtually confirms AI. >15 μg/dL makes AI unlikely. 3-15 μg/dL requires stimulation test."},{"drug":"ACTH","regimen":"PAI: HIGH (>2× upper limit — compensatory). SAI/TAI: LOW or normal (pituitary/hypothalamic failure)."},{"drug":"Sodium","regimen":"LOW in all types (84% of crisis patients). PAI: aldosterone deficiency + cortisol-related ADH excess. SAI/TAI: cortisol-related ADH excess only."},{"drug":"Potassium","regimen":"PAI: HIGH (aldosterone deficiency — unique to PAI). SAI/TAI: NORMAL (aldosterone preserved)."},{"drug":"Aldosterone","regimen":"PAI: LOW (adrenal destruction). SAI/TAI: NORMAL (RAAS intact)."},{"drug":"Renin","regimen":"PAI: HIGH (compensatory for low aldosterone). SAI/TAI: NORMAL."},{"drug":"Glucose","regimen":"LOW in all types. Worse in SAI (combined GH + cortisol deficiency). Especially common in children."},{"drug":"Calcium","regimen":"May be ELEVATED in PAI (decreased cortisol-mediated suppression of intestinal absorption, hypovolemia)."},{"drug":"CBC","regimen":"Normocytic anemia, lymphocytosis, eosinophilia (loss of cortisol-mediated eosinophil suppression)."},{"drug":"TSH","regimen":"May be elevated — either from loss of cortisol suppression of TSH, or concomitant autoimmune hypothyroidism (polyglandular syndrome)."}]},{"heading":"Key Distinguishing Features","body":"**Only in PAI:** Hyperkalemia, hyperpigmentation, elevated ACTH, elevated renin, low aldosterone\n**Only in SAI:** Other pituitary deficits (TSH, LH/FSH, GH, prolactin abnormalities), visual field defects\n**Suggests TAI:** History of chronic exogenous steroid use (oral, inhaled, topical, intra-articular, opioids)"}]'::jsonb,
 '[{"num":1,"text":"Bornstein SR, et al. Endocrine Society Clinical Practice Guideline. JCEM. 2016;101(2):364-389."},{"num":2,"text":"Husebye ES, et al. Adrenal Insufficiency. Lancet. 2021;397(10274):613-629."}]'::jsonb,
 false,
 2)
;

INSERT INTO info_pages (id, title, subtitle, sections, citations, shareable, sort_order) VALUES
('ai-sick-day-rules', 'Sick-Day Rules for Adrenal Insufficiency', 'When and how to increase your steroid dose',
 '[{"heading":"When to Increase Your Steroid Dose","body":"Your body needs MORE cortisol when you are sick, injured, or under stress. You must increase your steroid dose to prevent a dangerous drop in cortisol called an adrenal crisis."},{"heading":"Minor Illness (Cold, Mild Stomach Bug)","body":"• Fever over 100.4°F (38°C): DOUBLE your daily dose\n• Fever over 102.2°F (39°C): TRIPLE your daily dose\n• Continue the increased dose for 2-3 days until you feel better\n• Then return to your normal dose"},{"heading":"Moderate Illness or Injury","body":"• TRIPLE your daily dose or take hydrocortisone 50 mg by mouth twice a day\n• Seek medical attention\n• Continue increased dose until illness resolves, then taper back to normal over 2-3 days"},{"heading":"Unable to Keep Medicine Down (Vomiting)","body":"• If you vomit within 30 minutes of taking your steroid pill, you need your EMERGENCY INJECTION\n• Give yourself hydrocortisone 100 mg into your outer thigh muscle (IM injection)\n• GO TO THE EMERGENCY ROOM IMMEDIATELY after the injection\n• You will need IV steroids and fluids"},{"heading":"Surgery or Major Procedure","body":"• Tell your surgeon and anesthesiologist that you have adrenal insufficiency\n• You will need extra steroids before, during, and after the procedure\n• Your endocrinologist or surgeon should provide specific dosing instructions"},{"heading":"What to Always Carry","body":"• Medical alert bracelet or necklace\n• Steroid emergency card with your diagnosis and medications\n• Emergency hydrocortisone injection kit\n• Written copy of these sick-day rules\n• Extra supply of your oral steroid medication"},{"heading":"When to Go to the Emergency Room","body":"• Vomiting and unable to keep your steroid pills down\n• Fever not improving despite increased steroid dose\n• Dizziness, lightheadedness, or fainting\n• Confusion or difficulty staying awake\n• Severe abdominal pain\n• After using your emergency injection"}]'::jsonb,
 '[{"num":1,"text":"Bornstein SR, et al. Endocrine Society Clinical Practice Guideline. JCEM. 2016;101(2):364-389."},{"num":2,"text":"Burger-Stritt S, et al. Standardised Patient Education in Adrenal Insufficiency. Eur J Endocrinol. 2020;183(2):119-127."}]'::jsonb,
 true,
 3)
;

INSERT INTO info_pages (id, title, subtitle, sections, citations, shareable, sort_order) VALUES
('ai-special-populations', 'Special Populations in Adrenal Insufficiency', 'Pregnancy, pediatric CAH, chronic opioid users, checkpoint inhibitors',
 '[{"heading":"Pregnancy","body":"**Hydrocortisone is the glucocorticoid of choice** — inactivated by placental 11β-HSD2 (minimal fetal exposure). [1]\n\n• Increase HC by 20-40% in third trimester (physiologic cortisol rises in late pregnancy)\n• Morning sickness/hyperemesis may prevent oral absorption — use IM HC if vomiting\n• **Labor/delivery:** Stress-dose HC 100 mg IV at onset of labor, then 50 mg IV q8h until 24-48h postpartum\n• Cesarean section: treat as major surgery\n• Fludrocortisone may need increase (progesterone competes for mineralocorticoid receptor)\n• Interpret cortisol levels with caution — total cortisol rises in pregnancy due to increased cortisol-binding globulin"},{"heading":"Pediatric Congenital Adrenal Hyperplasia (CAH)","body":"**Most common cause of PAI in children** — 21-hydroxylase deficiency (>90% of cases). [2]\n\n• Maintenance: HC 6-10 mg/m²/day divided TID (lowest effective dose)\n• Fludrocortisone 50-200 μg/day for salt-wasting forms\n• Salt supplementation 1-2 g/day in infants\n• Monitor growth velocity — overtreatment suppresses linear growth\n• Newborn screening available in all US states (but can be missed)\n• Stress dosing: 30-50 mg/m²/day for illness, 50-100 mg/m² IV bolus for surgery\n• Parents must be trained in emergency IM injection technique\n• Sick-day rules education at every visit"},{"heading":"Chronic Opioid-Induced AI","body":"**Mechanism:** Opioids suppress hypothalamic CRH release → tertiary AI. [3]\n\n• Prevalence: ~15% of chronic opioid users\n• Higher risk with higher doses (>20 MME/day) and longer duration\n• No patient on <20 morphine milligram equivalents/day developed opioid-induced AI\n• Symptoms overlap with opioid side effects (fatigue, nausea) — easy to miss\n• Screen with AM cortisol in chronic opioid patients with fatigue or hypotension\n• May recover weeks to months after opioid cessation\n• Stress dosing needed until HPA recovery confirmed (AM cortisol >18 μg/dL off replacement)"},{"heading":"Immune Checkpoint Inhibitor-Induced","body":"**Ipilimumab (anti-CTLA-4):** Hypophysitis → secondary AI (highest risk, ~10% incidence). [4]\n**Pembrolizumab/nivolumab (anti-PD-1):** Primary adrenalitis → primary AI (less common).\n**Combined checkpoint therapy:** Highest overall endocrine toxicity risk.\n\n• Usually irreversible — lifelong hormone replacement needed\n• Do NOT hold cancer therapy — manage with hormone replacement and oncology co-management\n• Screen with AM cortisol + ACTH if new fatigue, hypotension, hyponatremia\n• MRI pituitary for suspected hypophysitis\n• Full anterior pituitary panel if SAI confirmed"}]'::jsonb,
 '[{"num":1,"text":"Lebbe M, Arlt W. What Is the Best Management Strategy for an Addison Patient During Pregnancy? Clin Endocrinol (Oxf). 2013;78(4):497-502."},{"num":2,"text":"Bornstein SR, et al. Endocrine Society Clinical Practice Guideline. JCEM. 2016;101(2):364-389."},{"num":3,"text":"de Vries F, et al. Opioids and Their Endocrine Effects: Systematic Review and Meta-Analysis. JCEM. 2020;105(3):1020-1029."},{"num":4,"text":"Hahner S, et al. Adrenal Insufficiency. Nat Rev Dis Primers. 2021;7(1):19."}]'::jsonb,
 false,
 4)
;

INSERT INTO info_pages (id, title, subtitle, sections, citations, shareable, sort_order) VALUES
('ai-steroid-equivalency', 'Corticosteroid Equivalency & Alternatives', 'Glucocorticoid and mineralocorticoid potency comparison',
 '[{"heading":"Glucocorticoid Equivalency Table","body":"","drugTable":[{"drug":"Hydrocortisone","regimen":"20 mg = 1× glucocorticoid potency. Duration: 8-12h. Mineralocorticoid: 1×. Preferred for replacement."},{"drug":"Cortisone","regimen":"25 mg equivalent. Duration: 8-12h. Mineralocorticoid: 0.8×. Requires hepatic conversion to cortisol (less reliable)."},{"drug":"Prednis(ol)one","regimen":"5 mg equivalent. Duration: 12-36h. Mineralocorticoid: 0.8×. Once-daily option; liquid available for children."},{"drug":"Methylprednisolone","regimen":"4 mg equivalent. Duration: 12-36h. Mineralocorticoid: 0.5×. IV alternative when HC unavailable."},{"drug":"Dexamethasone","regimen":"0.75 mg equivalent. Duration: 36-54h. Mineralocorticoid: 0×. Once-daily; does not interfere with cortisol assay."},{"drug":"Fludrocortisone","regimen":"— (not used for glucocorticoid replacement). Mineralocorticoid: 125×. Used for mineralocorticoid replacement in PAI only."}]},{"heading":"Why Hydrocortisone Is Preferred","body":"• **Physiologic** — structurally identical to endogenous cortisol\n• **Dual activity** — provides both glucocorticoid AND mineralocorticoid effect\n• **Short half-life** (~8-12h) — allows physiologic diurnal dosing (high AM, low PM)\n• **Lower growth suppression** in children vs longer-acting steroids\n• **Crisis doses (≥50 mg/day)** provide sufficient mineralocorticoid effect — no fludrocortisone needed"},{"heading":"When Alternatives Are Appropriate","body":"**Dexamethasone:** When cosyntropin stimulation test is planned (no cortisol assay interference). Once-daily dosing for adherence. Avoid in children long-term (growth suppression).\n\n**Prednisolone:** Once-daily dosing improves adherence. Liquid formulation for young children. Widely available.\n\n**Methylprednisolone:** IV alternative when hydrocortisone is unavailable in crisis setting.\n\n**NOTE:** All non-hydrocortisone alternatives lack adequate mineralocorticoid activity — patients with PAI on these agents MUST also take fludrocortisone."}]'::jsonb,
 '[{"num":1,"text":"Bornstein SR, et al. Endocrine Society Clinical Practice Guideline. JCEM. 2016;101(2):364-389."},{"num":2,"text":"Husebye ES, et al. Adrenal Insufficiency. Lancet. 2021;397(10274):613-629."}]'::jsonb,
 false,
 5)
;

COMMIT;
